---

###
### Lints all generic and json files in the whole git repository
###

name: reproducing issue
on:
  push:

jobs:
  build:
    runs-on: windows-latest

    name: "test job"
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@master
      - name: "List of processes 1"
        shell: bash
        run: |
          ls /usr/bin
          ps 
      - name: "Open browser"
        shell: bash
        run: |
          google-chrome www.gmail.com
      - name: "List of processes 2"
        shell: bash
        run: |
          ps
      - name: "Killing"
        shell: bash
        run: |
          kill -9 chrome
      - name: "List of processes 3"
        shell: powershell
        run: |
          Get-Process
