---

###
### Lints all generic and json files in the whole git repository
###

name: reproducing issue
on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'

    name: "[${{ matrix.version }}]"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Path
        run: |
          $path = "c:\msys64\usr\bin\bash;$env:PATH"
          echo "::set-env name=PATH::$path"
      - name: test
        shell: bash {0}
        run: |
          echo "$env:PATH"
          echo "$SHELL"
          python --version
          python -c 'while True: 1+1' &
          pid=$!
          ps
          sleep 3
          kill -9 $pid
          ps
